apiVersion: v2
name: umbrella
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: 0.1.0
    repository: "file://charts/common"
    condition: common.enabled

  - name: eg-gateway
    version: 0.1.0
    repository: "file://charts/eg-gateway"
    condition: eg-gateway.enabled

  - name: eg-identity
    version: 0.1.0
    repository: "file://charts/eg-identity"
    condition: eg-identity.enabled

  - name: eg-essay
    version: 0.1.0
    repository: "file://charts/eg-essay"
    condition: eg-essay.enabled

  - name: eg-interaction
    version: 0.1.0
    repository: "file://charts/eg-interaction"
    condition: eg-interaction.enabled

  - name: eg-frontend
    version: 0.1.0
    repository: "file://charts/eg-frontend"
    condition: eg-frontend.enabled
