# syntax=docker/dockerfile:1.7
FROM maven:3.9.12-eclipse-temurin-21 AS builder
WORKDIR /build
COPY . .

RUN --mount=type=cache,target=/root/.m2 \
    mvn -pl discovery-server -am clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine-3.23
WORKDIR /run
COPY --from=builder /build/discovery-server/target/discovery-server-*.jar discovery-server.jar
EXPOSE 8761
ENTRYPOINT ["java","-jar","/run/discovery-server.jar"]
