replicaCount: 1

image:
  registry: ""
  name: eg-essay-service
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    http: 10002
    grpc: 9082

envFrom:
  grpcConfig: grpc-config
  mongoSecret: eg-mongodb-admin-secrets
  identitySecret: eg-identity-secrets

env:
  commonConfig: common-config
  identitySecret: eg-identity-secrets
  mongoConfig: eg-essay-mongodb-config

